# FUNDING.yml

# VaxxVault Funding Information

# VaxxVault is the intellectual property of Henry Lawrence Cahill.
# For any inquiries, support, or funding opportunities related to VaxxVault,
# please use the following contact information:

# Physical Mail:
#   Henry Lawrence Cahill
#   8751 Houston St.
#   Lenexa, Kansas, United States 66227

# Electronic Mail:
#   - henrycahill97@gmail.com
#   - henry.lawrence.cahill@howtoosoftware.com

# Telephone:
#   (913) 608-3187

# Funding Platforms:
# If you have accounts on any funding platforms, list them below.

#github: [Henry-Cahill]
#patreon: []
#open_collective: []
#ko_fi: []
#tidelift: []
#custom:

  # You can add custom funding links here.
  # Example:
  # - https://www.your-custom-funding-page.com

  # Since you might not have specific funding platforms set up yet,
  # interested parties can reach out via the contact information provided above.


# These are supported funding model platforms

github: [Henry-Cahill] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: # Replace with a single Patreon username
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: # Replace with a single Liberapay username
#issuehunt: # Replace with a single IssueHunt username
#lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
#polar: # Replace with a single Polar username
#buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
#thanks_dev: # Replace with a single thanks.dev username
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
